WebApplication4/Controllers/EmpleadosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication4.Models;


namespace WebApplication4.Controllers
{
    public class EmpleadosController : Controller
    {
        private EmpleadosContext db = new EmpleadosContext();

        // GET: Empleados
        public ActionResult Index(string Nombre, string Departamento, string Estatus)
        {
            var proveider = from s in db.Empleado select s;

            if (!String.IsNullOrEmpty(Nombre) && !String.IsNullOrEmpty(Estatus))
            {
                proveider = proveider.Where(JavaScript => JavaScript.Nombre.Contains(Nombre) && JavaScript.Estatus.ToString().Contains(Estatus));
                return View(proveider);
            }
            else if (!String.IsNullOrEmpty(Departamento) && !String.IsNullOrEmpty(Estatus))

            {
                proveider = proveider.Where(JavaScript => JavaScript.Departamento.Contains(Departamento) && JavaScript.Estatus.ToString().Contains(Estatus));
                
                return View(proveider);
            }
            else
            {
                
                proveider = proveider.Where(JavaScript => JavaScript.Estatus.ToString().Contains(Estatus));
                return View(proveider);
            }
            

            
        }

        // GET: Empleados/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleado.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // GET: Empleados/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Empleados/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CodigoEmpleado,Nombre,Apellido,Telefono,Departamento,Cargo,FechaIngreso,Salario,Estatus")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.Empleado.Add(empleados);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(empleados);
        }

        // GET: Empleados/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleado.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // POST: Empleados/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CodigoEmpleado,Nombre,Apellido,Telefono,Departamento,Cargo,FechaIngreso,Salario,Estatus")] Empleados empleados)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleados).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(empleados);
        }

        // GET: Empleados/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleados empleados = db.Empleado.Find(id);
            if (empleados == null)
            {
                return HttpNotFound();
            }
            return View(empleados);
        }

        // POST: Empleados/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleados empleados = db.Empleado.Find(id);
            db.Empleado.Remove(empleados);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PG3</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
   
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PG3", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Mantenimiento", "Index", "Empleados", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Nominas", "Index", "Nominas", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Salidas", "Index", "Salidas", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Vacaciones", "Index", "Vacaciones", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Permisos", "Index", "Permisos", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Licencias", "Index", "Licencias", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="text-align: center">
            <p >&copy; @DateTime.Now.Year - (2017-4824 & 2017-4622) ©Copyright-Derechos Reservados</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>